<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net6.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>OpResult</PackageId>
    <Version>0.1.0</Version>
    <Authors>RokyZevon</Authors>
    <Description>A small .NET Result Pattern library for explicit Ok/Err business flows.</Description>
    <PackageTags>result;result-pattern;error-handling;functional</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/RokyZevon/OpResult</PackageProjectUrl>
    <RepositoryUrl>https://github.com/RokyZevon/OpResult</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
